backend:
  name: git-gateway
  branch: master

display_url: https://utopia2019.com
# publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: "/uploads"

collections:

  # Blog posts
  - name: "post"
    extension: "markdown"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
    editor:
      preview: false

  # Speakers
  - name: "speaker"
    extension: "markdown"
    label: "Speakers"
    folder: "content/speakers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Image", name: "image", widget: "image", hint: "Make sure your image is no more than 200px wide and tall before uploading it. Large images will slow down the experience and irritate users."}
      - {label: "Order", name: "order", widget: "number", min: 0, valueType: "int", hint: "The lower the number, the higher the speaker will appear"}
    editor:
      preview: false

  # Event
  - name: "event"
    extension: "markdown"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Speaker", name: "speaker_name", widget: "relation", collection: "speaker", valueField: "title", searchFields: ["title"]}
    editor:
      preview: false

  # Info
  - name: "info"
    extension: "markdown"
    label: "Info"
    folder: "content/info"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number", min: 0, valueType: "int", hint: "The lower the number, the higher this info snippet will appear"}
      - {label: "Body", name: "body", widget: "markdown"}
    editor:
      preview: false

  # Strand
  # - name: "strand"
  #   extension: "markdown"
  #   label: "Strands"
  #   folder: "content/strands"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Name", name: "title", widget: "string"}
  #   editor:
  #     preview: false

  # # Venue
  # - name: "venue"
  #   extension: "markdown"
  #   label: "Venues"
  #   folder: "content/venues"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - {label: "Name", name: "title", widget: "string"}
  #   editor:
  #     preview: false

  # Unique pages
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home page"
        name: "home"
        file: "content/pages/index.markdown"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "index"}
          - {label: "Headline", name: "headline", widget: "string"}
          - {label: "Subheadline", name: "subheadline", widget: "string"}
          - {label: "Headline", name: "explanationHeadline", widget: "string"}
          - {label: "Subheadline", name: "explanationSubheadline", widget: "string"}
          - {label: "When", name: "when", widget: "string"}
          - {label: "Where", name: "where", widget: "string"}
          - {label: "Testimonial quote", name: "testimonial", widget: "string"}
          - {label: "Citation name", name: "citationName", widget: "string"}
          - {label: "Citation role", name: "citationRole", widget: "string"}
          - {label: "Venue address", name: "address", widget: "string"}
          - {label: "Venue info", name: "venueInfo", widget: "string"}
          - {label: "Registration info", name: "venueInfo", widget: "string"}

      - label: "Speakers page"
        name: "speakers"
        file: "content/pages/speakers.markdown"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "speakers"}
          - {label: "Lede", name: "lede", widget: "string"}

      - label: "Blog page"
        name: "blog"
        file: "content/pages/blog.markdown"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "blog"}
          - {label: "Lede", name: "lede", widget: "string"}

      - label: "Privacy notice"
        name: "privacy-policy"
        file: "content/pages/privacy-notice.markdown"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "privacy-notice"}
          - {label: "Body", name: "body", widget: "markdown"}